from _typeshed import Incomplete

class Chunker:
    strategy: Incomplete
    window_size: Incomplete
    overlap: Incomplete
    def __init__(self, strategy: dict) -> None: ...
    @staticmethod
    def clean_text(text: str) -> str: ...
    def __call__(self, text: str) -> list[str]: ...
    def paragraph_chunking(self, text: str) -> list[str]: ...
    def sliding_window_chunking(self, text: str) -> list[str]: ...
