from _typeshed import Incomplete
from typing import Any

class Storage:
    memory_file: Incomplete
    def __init__(self, memory_file: str = "long_memory.pkl") -> None: ...
    def save_to_disk(self, data: list[dict[str, Any]]) -> None: ...
    def load_from_disk(self) -> list[dict[str, Any]]: ...
